[
    {
      "id": 1,
      "display_name": "Chelsey Dietrich",
      "first_name": "Chelsey",
      "last_name": "Dietrich",
      "user_principal_name": "54892@thresholds.org",
      "object_id": "eeeeeeee-1111-4444-aaaa-dddddddddddd",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Community Support Specialist",
      "program_name": "Bridge West",
      "team_name": "Bridge West CSI",
      "employee_id": 54892,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "2240 W Ogden Ste 300",
      "office_location": "2240 W Ogden",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60612-4881",
      "country": null,
      "business_phone": "1-254-954-1289",
      "mobile_phone": null,
      "email": "Chelsey.Dietrich@thresholds.org",
      "fax_number": null,
      "mail_nickname": "54892",
      "department_code": "0654",
      "skill_code": null,
      "pronouns": "She/Her/Hers",
      "team_voice_number": "1-463-123-4447"
    },
    {
      "id": 2,
      "display_name": "Glenna Reichert",
      "first_name": "Glenna",
      "last_name": "Reichert",
      "user_principal_name": "39873@thresholds.org",
      "object_id": "ffffffff-2222-4444-aaaa-dddddddddddd",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Education and Employment Support Specialist",
      "program_name": "Employment Services",
      "team_name": "IPS Deaf/MindStrong/Emerg",
      "employee_id": 39873,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "2847 N Clark St",
      "office_location": "Lakeview Health Center",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60657-5207",
      "country": null,
      "business_phone": "1-775-976-6794",
      "mobile_phone": null,
      "email": "Glenna.Reichert@thresholds.org",
      "fax_number": null,
      "mail_nickname": "39873",
      "department_code": "0228",
      "skill_code": "MHP",
      "pronouns": null,
      "team_voice_number": null
    },
    {
      "id": 3,
      "display_name": "Nicholas Ellsworth",
      "first_name": "Nicholas",
      "last_name": "Ellsworth",
      "user_principal_name": "69238@thresholds.org",
      "object_id": "eeeeeeee-1111-3333-aaaa-hhhhhhhhhhhh",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Nurse Care Coordinator",
      "program_name": "Williams Coordination",
      "team_name": "Williams Int Healthcare",
      "employee_id": 69238,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "4423 N Ravenswood Ave",
      "office_location": "Phyllis and Perry Schwartz Center for Integrated Health",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60640-5802",
      "country": null,
      "business_phone": "1-493-170-9623",
      "mobile_phone": null,
      "email": "Nicholas.Ellsworth@thresholds.org",
      "fax_number": null,
      "mail_nickname": "69238",
      "department_code": "0630",
      "skill_code": "RN",
      "pronouns": "He/Him/His",
      "team_voice_number": "1-493-291-0392"
    },
    {
      "id": 4,
      "display_name": "Aaron Neal",
      "first_name": "Aaron",
      "last_name": "Neal",
      "user_principal_name": "16030@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Director, Homeless Contracts Compliance",
      "program_name": "Housing and Real Estate",
      "team_name": "Homeless Grant Compliance",
      "employee_id": 16030,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "Phyllis and Perry Schwartz Center for Integrated Health",
      "office_location": "4423 N Ravenswood Ave",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60640-5802",
      "country": null,
      "business_phone": "1-773-572-5298",
      "mobile_phone": null,
      "email": "Aaron.Neal@thresholds.org",
      "fax_number": null,
      "mail_nickname": "16030",
      "department_code": "0917",
      "skill_code": null,
      "pronouns": null,
      "team_voice_number": null
    },
    {
      "id": 5,
      "display_name": "Abigail Hernandez",
      "first_name": "Abigail",
      "last_name": "Hernandez",
      "user_principal_name": "20376@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Intake Specialist - Masters",
      "program_name": "Access & Implementation",
      "team_name": "Access & Impl Team D",
      "employee_id": 20376,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "Phyllis and Perry Schwartz Center for Integrated Health",
      "office_location": "4423 N Ravenswood Ave",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60640-5802",
      "country": null,
      "business_phone": "1-773-432-6356",
      "mobile_phone": null,
      "email": "Abigail.Hernandez@thresholds.org",
      "fax_number": null,
      "mail_nickname": "20376",
      "department_code": "0051",
      "skill_code": "QMHP",
      "pronouns": null,
      "team_voice_number": null
    },
    {
      "id": 7,
      "display_name": "Alex Reyes",
      "first_name": "Alex",
      "last_name": "Reyes",
      "user_principal_name": "20227@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Community Support Specialist",
      "program_name": "Bridge Southwest",
      "team_name": "Bridge Southwest CST 1",
      "employee_id": 20227,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "Bridge Southwest",
      "office_location": "3638 S Kedzie Ave",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60632-2727",
      "country": null,
      "business_phone": "1-773-432-6148",
      "mobile_phone": null,
      "email": "Alex.Reyes@thresholds.org",
      "fax_number": null,
      "mail_nickname": "20227",
      "department_code": "0590",
      "skill_code": "MHP",
      "pronouns": null,
      "team_voice_number": "1-773-537-3170"
    },
    {
      "id": 8,
      "display_name": "Andy Brower",
      "first_name": "Andy",
      "last_name": "Brower",
      "user_principal_name": "9876@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Program Director",
      "program_name": "Dincin",
      "team_name": "Dincin ACT 1",
      "employee_id": 9876,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "Phyllis and Perry Schwartz Center for Integrated Health",
      "office_location": "4423 N Ravenswood Ave",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60640-5802",
      "country": null,
      "business_phone": "1-773-572-5432",
      "mobile_phone": null,
      "email": "Andrew.Brower@thresholds.org",
      "fax_number": null,
      "mail_nickname": "9876",
      "department_code": "0509",
      "skill_code": "LPHA",
      "pronouns": "He/Him/His",
      "team_voice_number": "1-773-572-5228"
    },
    {
      "id": 9,
      "display_name": "Elizabeth Julian, RN",
      "first_name": "Elizabeth",
      "last_name": "Julian,",
      "user_principal_name": "20053@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Nurse Care Coordinator, CCBHC",
      "program_name": "Dincin",
      "team_name": "Dincin Outpatient",
      "employee_id": 20053,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "Phyllis and Perry Schwartz Center for Integrated Health",
      "office_location": "4423 N Ravenswood Ave",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60640-5802",
      "country": null,
      "business_phone": "1-773-572-5494",
      "mobile_phone": null,
      "email": "Elizabeth.Julian@thresholds.org",
      "fax_number": null,
      "mail_nickname": "20053",
      "department_code": "0515",
      "skill_code": "RN",
      "pronouns": "She/Her/Hers",
      "team_voice_number": null
    },
    {
      "id": 10,
      "display_name": "Erika Ware",
      "first_name": "Erika",
      "last_name": "Ware",
      "user_principal_name": "20808@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Desk Clerk",
      "program_name": "South Suburbs",
      "team_name": "South SubChicago Heights",
      "employee_id": 20808,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "Chicago Heights",
      "office_location": "619 W 15Th St",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60411-3817",
      "country": null,
      "business_phone": null,
      "mobile_phone": null,
      "email": "Erika.Ware@thresholds.org",
      "fax_number": null,
      "mail_nickname": "20808",
      "department_code": "0330",
      "skill_code": "MHP",
      "pronouns": null,
      "team_voice_number": "1-773-537-3886"
    },
    {
      "id": 11,
      "display_name": "Ingrid Stovall",
      "first_name": "Ingrid",
      "last_name": "Stovall",
      "user_principal_name": "1830@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Team Leader",
      "program_name": "Southside Housing",
      "team_name": "SSH Coles House",
      "employee_id": 1830,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "Coles House",
      "office_location": "5493 S Cornell Ave #99",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60615-5641",
      "country": null,
      "business_phone": "1-773-537-3861",
      "mobile_phone": null,
      "email": "Ingrid.Booker@thresholds.org",
      "fax_number": null,
      "mail_nickname": "1830",
      "department_code": "0175",
      "skill_code": "MHP",
      "pronouns": null,
      "team_voice_number": "1-773-537-3853"
    },
    {
      "id": 12,
      "display_name": "Jaclyn Gass",
      "first_name": "Jaclyn",
      "last_name": "Gass",
      "user_principal_name": "16969@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Community Support Specialist - Masters",
      "program_name": "South Suburbs",
      "team_name": "South Suburbs CSI",
      "employee_id": 16969,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "South Suburbs",
      "office_location": "12145 Western Ave",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60406-1387",
      "country": null,
      "business_phone": null,
      "mobile_phone": null,
      "email": "Jaclyn.Gass@thresholds.org",
      "fax_number": null,
      "mail_nickname": "16969",
      "department_code": "0311",
      "skill_code": "QMHP",
      "pronouns": null,
      "team_voice_number": "1-773-537-3835"
    },
    {
      "id": 13,
      "display_name": "Jay Baumann",
      "first_name": "Jay",
      "last_name": "Baumann",
      "user_principal_name": "20411@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Crisis Support Specialist, Living Room",
      "program_name": "Crisis Response",
      "team_name": "Living Room Forever Hope",
      "employee_id": 20411,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "Phyllis and Perry Schwartz Center for Integrated Health",
      "office_location": "4423 N Ravenswood Ave",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60640-5802",
      "country": null,
      "business_phone": null,
      "mobile_phone": null,
      "email": "Jay.Baumann@thresholds.org",
      "fax_number": null,
      "mail_nickname": "20411",
      "department_code": "0542",
      "skill_code": "MHP",
      "pronouns": "He/They",
      "team_voice_number": "1-773-537-3680"
    },
    {
      "id": 14,
      "display_name": "Jennie Henry",
      "first_name": "Jennie",
      "last_name": "Henry",
      "user_principal_name": "17530@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Desk Clerk",
      "program_name": "Austin Apartments",
      "team_name": "Austin Apartments CSI",
      "employee_id": 17530,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "Austin Apartments",
      "office_location": "334 N Menard Ave",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60644-2157",
      "country": null,
      "business_phone": null,
      "mobile_phone": null,
      "email": "Jennie.Henry@thresholds.org",
      "fax_number": null,
      "mail_nickname": "17530",
      "department_code": "0750",
      "skill_code": null,
      "pronouns": null,
      "team_voice_number": "1-773-537-3051"
    },
    {
      "id": 15,
      "display_name": "Joe Tisdale",
      "first_name": "Joe",
      "last_name": "Tisdale",
      "user_principal_name": "20745@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Desk Clerk",
      "program_name": "Northside Housing",
      "team_name": "Humboldt Apartments",
      "employee_id": 20745,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "Steven Carroll Residence",
      "office_location": "1819 N Humboldt Blvd",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60647-5029",
      "country": null,
      "business_phone": null,
      "mobile_phone": null,
      "email": "Joe.Tisdale@thresholds.org",
      "fax_number": null,
      "mail_nickname": "20745",
      "department_code": "1120",
      "skill_code": "RSA",
      "pronouns": null,
      "team_voice_number": null
    },
    {
      "id": 16,
      "display_name": "Kelsey Adams",
      "first_name": "Kelsey",
      "last_name": "Adams",
      "user_principal_name": "20535@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Community Support Specialist - Masters",
      "program_name": "Bridge South",
      "team_name": "Bridge South ACT",
      "employee_id": 20535,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "Bridge South (Thresholds Entrance)",
      "office_location": "4656 S Emerald Ave",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60609-4412",
      "country": null,
      "business_phone": "1-773-537-3324",
      "mobile_phone": null,
      "email": "Kelsey.Adams@thresholds.org",
      "fax_number": null,
      "mail_nickname": "20535",
      "department_code": "0621",
      "skill_code": "QMHP",
      "pronouns": null,
      "team_voice_number": "1-773-537-3310"
    },
    {
      "id": 17,
      "display_name": "LaTaylor Johnson",
      "first_name": "LaTaylor",
      "last_name": "Johnson",
      "user_principal_name": "20711@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Crisis Support Specialist, Living Room",
      "program_name": "Crisis Response",
      "team_name": "Living Room Forever Hope",
      "employee_id": 20711,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "Phyllis and Perry Schwartz Center for Integrated Health",
      "office_location": "4423 N Ravenswood Ave",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60640-5802",
      "country": null,
      "business_phone": null,
      "mobile_phone": null,
      "email": "LaTaylor.Johnson@thresholds.org",
      "fax_number": null,
      "mail_nickname": "20711",
      "department_code": "0542",
      "skill_code": "RSA",
      "pronouns": null,
      "team_voice_number": "1-773-537-3680"
    },
    {
      "id": 18,
      "display_name": "Laura Sage",
      "first_name": "Laura",
      "last_name": "Sage",
      "user_principal_name": "20733@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Intern",
      "program_name": "Student Internship Prog",
      "team_name": "Student Internship Prog",
      "employee_id": 20733,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "4101 N Ravenswood Ave",
      "office_location": "4101 N Ravenswood Ave",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60613-2193",
      "country": null,
      "business_phone": null,
      "mobile_phone": null,
      "email": "Laura.Sage@thresholds.org",
      "fax_number": null,
      "mail_nickname": "20733",
      "department_code": "0099",
      "skill_code": "MHP",
      "pronouns": null,
      "team_voice_number": null
    },
    {
      "id": 19,
      "display_name": "Marcie Sasewich",
      "first_name": "Marcie",
      "last_name": "Sasewich",
      "user_principal_name": "20181@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Desk Clerk",
      "program_name": "Support (4101)",
      "team_name": "Administration Support",
      "employee_id": 20181,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "4101 N Ravenswood Ave",
      "office_location": "4101 N Ravenswood Ave",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60613-2193",
      "country": null,
      "business_phone": null,
      "mobile_phone": null,
      "email": "Marcie.Sasewich@thresholds.org",
      "fax_number": null,
      "mail_nickname": "20181",
      "department_code": "0940",
      "skill_code": "RSA",
      "pronouns": null,
      "team_voice_number": "1-773-572-5299"
    },
    {
      "id": 20,
      "display_name": "Nate Kehoe",
      "first_name": "Nate",
      "last_name": "Kehoe",
      "user_principal_name": "19852@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Teacher's Aide, YAP",
      "program_name": "YAP Residential",
      "team_name": "YAP Loren Juhl School",
      "employee_id": 19852,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "YAP Building",
      "office_location": "4219 N Lincoln Ave",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60618-2901",
      "country": null,
      "business_phone": null,
      "mobile_phone": null,
      "email": "Nate.Kehoe@thresholds.org",
      "fax_number": null,
      "mail_nickname": "19852",
      "department_code": "0072",
      "skill_code": "RSA",
      "pronouns": null,
      "team_voice_number": "1-773-537-3280"
    },
    {
      "id": 21,
      "display_name": "Quiana Starling",
      "first_name": "Quiana",
      "last_name": "Starling",
      "user_principal_name": "20571@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Community Support Specialist",
      "program_name": "Bridge Southeast",
      "team_name": "Bridge Southeast CST 4",
      "employee_id": 20571,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "Bridge Southeast",
      "office_location": "6337 S Woodlawn",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60637-3707",
      "country": null,
      "business_phone": null,
      "mobile_phone": null,
      "email": "Quiana.Starling@thresholds.org",
      "fax_number": null,
      "mail_nickname": "20571",
      "department_code": "0092",
      "skill_code": "RSA",
      "pronouns": null,
      "team_voice_number": "1-773-537-3056"
    },
    {
      "id": 22,
      "display_name": "Shakala Link",
      "first_name": "Shakala",
      "last_name": "Link",
      "user_principal_name": "19484@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Team Leader, Revenue Cycle Management",
      "program_name": "Billing & Revenue Cycle",
      "team_name": "Billing/Revenue Cycle",
      "employee_id": 19484,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "120 S LaSalle",
      "office_location": "120 S Lasalle St Ste 1410",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60603-3579",
      "country": null,
      "business_phone": "1-773-432-6225",
      "mobile_phone": null,
      "email": "Shakala.Link@thresholds.org",
      "fax_number": null,
      "mail_nickname": "19484",
      "department_code": "0936",
      "skill_code": "RSA",
      "pronouns": "She/Her/Hers",
      "team_voice_number": null
    },
    {
      "id": 23,
      "display_name": "Sonja Bozic",
      "first_name": "Sonja",
      "last_name": "Bozic",
      "user_principal_name": "20838@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Community Support Specialist",
      "program_name": "McHenry County",
      "team_name": "McHenry CSI 3",
      "employee_id": 20838,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "McHenry",
      "office_location": "2030 N Seminary Ave",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60098-2626",
      "country": null,
      "business_phone": null,
      "mobile_phone": null,
      "email": "Sonja.Bozic@thresholds.org",
      "fax_number": null,
      "mail_nickname": "20838",
      "department_code": "0379",
      "skill_code": "MHP",
      "pronouns": null,
      "team_voice_number": null
    },
    {
      "id": 24,
      "display_name": "Stefanie Muisenga",
      "first_name": "Stefanie",
      "last_name": "Muisenga",
      "user_principal_name": "17866@thresholds.org",
      "object_id": "00000000-0000-0000-0000-000000000000",
      "user_type": "Member",
      "creation_type": null,
      "created_datetime": null,
      "last_password_change": null,
      "invitation_state": null,
      "external_state_change_datetime": null,
      "passwordpolicy": "DisablePasswordExpiration",
      "preferred_language": null,
      "job_title": "Team Leader, CST",
      "program_name": "McHenry County",
      "team_name": "McHenry CST 2",
      "employee_id": 17866,
      "employee_type": "FT",
      "employee_hire_date": null,
      "street_address": "McHenry",
      "office_location": "2030 N Seminary Ave",
      "city": "Chicago",
      "state": "IL",
      "postal_code": "60098-2626",
      "country": null,
      "business_phone": "1-815-679-4633",
      "mobile_phone": null,
      "email": "Stefanie.Muisenga@thresholds.org",
      "fax_number": null,
      "mail_nickname": "17866",
      "department_code": "0378",
      "skill_code": "QMHP",
      "pronouns": "She/Her/Hers",
      "team_voice_number": "1-815-679-4604"
    }
  ]